### ISSUE TITLE
dropdown options for announcement start date

### ISSUE THREAD

**Issue by kangni-wang** [hmc-godaddy-clinic-16/editor-section#11]
<textbox> <dropdown: day/week/month/year>
or
<dropdown: 1day/3day/1week/2weeks/1month.....>

**Comment by maureennaval** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Fixes/Feature Wrap-Ups](https://trello.com/c/16ydfDrl/35-bug-fixes-feature-wrap-ups)

**Comment by maureennaval** [comment]
Or alternatively: (1) Increment minute field by 5/10/15? minutes (2) Allow user to type in time field
