### ISSUE TITLE
Bug: Editor section data prepopulation

### ISSUE THREAD

**Issue by lbnelson** [hmc-godaddy-clinic-16/editor-section#12]
The call to the database happens asynchronously, but the editor fields are updated immediately from the store. This means that the information in the editor section doesn't get updated with the information from the database.

**Comment by Koverbay** [comment]
UPDATE: Fixed for inputbox and richtexteditor. Scheduler/datetimepicker still needs fix

**Comment by maureennaval** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Fixes/Feature Wrap-Ups](https://trello.com/c/16ydfDrl/35-bug-fixes-feature-wrap-ups)
