### ISSUE TITLE
Individual Announcement IDs for DB

### ISSUE THREAD

**Issue by lbnelson** [hmc-godaddy-clinic-16/editor-section#16]
Since we don't have a user authentication system, all information updated in the editor is currently written to the same item in the database. Instead, we should have a way to write to different announcements in the database even if it is hard-coded.

**Comment by maureennaval** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Fixes/Feature Wrap-Ups](https://trello.com/c/16ydfDrl/35-bug-fixes-feature-wrap-ups)

**Comment by lbnelson** [comment]
See google doc linked in slack/in the clinic google drive for announcement ids.
