### ISSUE TITLE
Checkbox in datetimepicker not checking properly

### ISSUE THREAD

**Issue by Koverbay** [hmc-godaddy-clinic-16/editor-section#23]
clicking on the text on the bottom checkbox (end never) checks/unchecks the top checkbox (start now)

**Comment by maureennaval** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Fixes/Feature Wrap-Ups](https://trello.com/c/16ydfDrl/35-bug-fixes-feature-wrap-ups)
