### ISSUE TITLE
Double Posting

### ISSUE THREAD

**Issue by Koverbay** [hmc-godaddy-clinic-16/editor-section#54]
The most updated commit on facebook branch (post to FB page with scheduling) will post an announcement to the page twice, when scheduling is on AND off.

Previous commit (the one before merging) doesn't have the double-posting bug.

**Comment by LazyConi** [comment]
The most uptodate commit on facebook branch (post to FB page with scheduling) will post an announcement to the page twice, when scheduling is on AND off.

Previous commit (the one before merging) doesn't have the double-posting bug.
