### ISSUE TITLE
Date/time picker styling

### ISSUE THREAD

**Issue by lbnelson** [hmc-godaddy-clinic-16/editor-section#9]
The updated date/time picker needs to be styled to match the rest of the UI

**Comment by maureennaval** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Fixes/Feature Wrap-Ups](https://trello.com/c/16ydfDrl/35-bug-fixes-feature-wrap-ups)

**Comment by maureennaval** [comment]
- General styling of buttons completed
- Checkbox does not uncheck (problem with :uncheck selector?)
